### ISSUE TITLE
自定义body没生效

### ISSUE THREAD

**Issue by panda-men** [Tinywan/webman-exception-handler#12]
问题描述
Exception 异常插件，自定义body没生效，不知道是不是使用方式不对
![image](https://github.com/Tinywan/webman-exception/assets/16631289/28d9096e-e0d3-4271-b2e4-fc0b073ad2d5)

根据插件文档配置
![image](https://github.com/Tinywan/webman-exception/assets/16631289/6eb9cbac-0ef2-42cf-8742-9c93208a5f0e)

配置代码
![image](https://github.com/Tinywan/webman-exception/assets/16631289/82c9e19c-1869-4e84-8512-e086948307af)

接口返回
![image](https://github.com/Tinywan/webman-exception/assets/16631289/42055cdd-01be-4dcf-aea7-921c8973b549)

**Comment by Tinywan** [comment]
是最新版本吗？

**Comment by Tinywan** [comment]
这个自定义是指可以自定义返回的数据格式，而不是返回的具体内容

**Comment by Tinywan** [comment]
> 自定义状态码，响应http状态码

![image](https://github.com/Tinywan/webman-exception/assets/14959876/b7c122ae-3857-457c-a0a4-7933cde4e18b)

**Comment by panda-men** [comment]
![image](https://github.com/Tinywan/webman-exception/assets/16631289/12a467fc-4133-4b8e-8d31-84b4610f0277)
![image](https://github.com/Tinywan/webman-exception/assets/16631289/ee82a981-8033-4e53-ae88-9fe3241fc637)
![image](https://github.com/Tinywan/webman-exception/assets/16631289/6334b9e7-fe79-4c6e-a972-a54659690334)
![image](https://github.com/Tinywan/webman-exception/assets/16631289/20b4214c-ccb3-4ccf-b469-78bb017713fb)
您的意思是返回请求http状态码而不是返回body里面code的值？

**Comment by Tinywan** [comment]
是自定义HTTP状态码哦
