### ISSUE TITLE
抛出ServerErrorHttpException 异常时 响应返回msg一直为空

### ISSUE THREAD

**Issue by YuhSong** [Tinywan/webman-exception-handler#17]
![image](https://github.com/Tinywan/webman-exception/assets/64961024/4102f6b3-b149-477b-9db6-ed5ad1a938de)
![image](https://github.com/Tinywan/webman-exception/assets/64961024/ea3255a3-fef7-4049-85a7-6a84b4f0b9b5)
![image](https://github.com/Tinywan/webman-exception/assets/64961024/f69e6052-057d-4b3e-a116-ece8b4cca172)
![image](https://github.com/Tinywan/webman-exception/assets/64961024/9485fc80-b2a0-426a-8029-1178f2fd041c)
ServerErrorHttpException 继承 BaseException 异常信息获取应该直接为$this->errorMessage 但是solveExtraException方法中使用$e->getMessage() 重新赋值 而BaseException异常不支持通过$e->getMessage()获取异常信息

**Comment by Tinywan** [comment]
你这个是最新版本吗？

**Comment by Tinywan** [comment]
> 你这个是最新版本吗？

这边是没问题的

![image](https://github.com/Tinywan/webman-exception/assets/14959876/20082fe1-ab18-4ab2-84e5-3c15cc725461)

**Comment by YuhSong** [comment]
> > 你这个是最新版本吗？
> 
> 这边是没问题的
> 
> ![图像](https://private-user-images.githubusercontent.com/14959876/337870159-20082fe1-ab18-4ab2-84e5-3c15cc725461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MDM3NjAsIm5iZiI6MTcxNzkwMzQ2MCwicGF0aCI6Ii8xNDk1OTg3Ni8zMzc4NzAxNTktMjAwODJmZTEtYWIxOC00YWIyLTg0ZTUtM2MxNWNjNzI1NDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAzMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2QxNzBkOTgxYjI0YTZiMThiYjI2ZjBkNmVhYjQ5MjMwYzBhZTM4NGE1NTM4MTBkNDRhMTg1OGM2ZGQyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8vlG9dT1YWF0jf4OWH9cfSWg8UI2a3jnj6k3ljOh3mk)

不好意思哈 之前用的7.3 composer拉的1.3版本的 升级之后好了

**Comment by Tinywan** [comment]
好的
