### ISSUE TITLE
event 问题

### ISSUE THREAD

**Issue by krissss** [Tinywan/webman-exception-handler#2]
app.php 下的 event 与 `webman/event` 存在冲突

![image](https://user-images.githubusercontent.com/10680903/185023492-c2c6f1cf-19a1-4571-8faa-4a05141ae061.png)

**Comment by Tinywan** [comment]
这个能详细说明一下吗？

**Comment by krissss** [comment]
安装 webman/event 之后启动 webman 就报这些提示了

**Comment by Tinywan** [comment]
不安装 webman/event 就没问题是吗？webman/event 是群主最近才出来的，你先看看能不能提交个PR，晚点我看看怎么回事。

**Comment by Tinywan** [comment]
@krissss 冲突问题已解决，请更新到最新版本 `v1.0.0`
