### ISSUE TITLE
扩展自己的 Handler

### ISSUE THREAD

**Issue by bilulanlv** [Tinywan/webman-exception-handler#5]
使用文档中的方法，拓展自己的Handler，并不能生效。请问还需要其他配置吗？

namespace support;

use hg\apidoc\exception\HttpException;
use Tinywan\ExceptionHandler\Handler;

class ErrorHandler extends Handler
{
    /**
     * @inheritDoc
     */
    protected function solveExtraException(\Throwable $e): void
    {
        // 当前项目下的异常扩展
        if ($e instanceof HttpException) {
            $this->errorMessage = 'Apidoc异常';
            $this->statusCode = 401;
            return;
        }
        parent::solveExtraException($e);
    }
}

**Comment by Tinywan** [comment]
不需要
