### ISSUE TITLE
你好，可以增加一个配置 data里不返回内置的那几个变量不？

### ISSUE THREAD

**Issue by jetlong** [Tinywan/webman-exception-handler#8]
![image](https://github.com/Tinywan/webman-exception/assets/6326231/9a9b43fc-81b4-4243-aa35-180131963eef)

需要这样的结果：
![image](https://github.com/Tinywan/webman-exception/assets/6326231/9664c82d-75a3-4216-a9c3-4d546f626a04)

不需要这样的结果：
![image](https://github.com/Tinywan/webman-exception/assets/6326231/0c88143f-56b7-4b1a-a6a1-72598ec8a132)

**Comment by Tinywan** [comment]
你可以重写该方法就行了

**Comment by jetlong** [comment]
好的，我试试，谢谢
